routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Artisan;

Route::get('/', function () {
    return redirect()->route('home');
});

Route::get('/home', function () {
    return redirect()->route('filter');
})->name('home');

Route::get('/filter/{filter?}', 'FilterController@indexFilter')->name('filter');
Route::get('/filter2', 'FilterController@indexFilter2')->name('filter2');
//Axio Endpoint
Route::get('/json-filter2', 'FilterController@filter2Json');

Route::get('/filter3/{sort?}', 'FilterController@indexFilter3')->name('filter3');
//Axio Endpoint
Route::get('/json-filter3', 'FilterController@filter3Json');

Route::get('/api', 'HomeController@getDataFromApi');

Route::get('/mass/destroy', 'HomeController@massDestroy')->name('mass.destroy');

Artisan::call('view:clear');

app/EmployeeWorkHours.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class EmployeeWorkHours
 * Created by PhpStorm.
 * User: Faks
 * GitHub: https://github.com/Faks
 *
 * @category PHP
 * @package  App
 * @author   Oskars Germovs <solumdesignum@gmail.com>
 * @license  https://opensource.org/licenses/MIT MIT Licence
 * @link     http://solum-designum.com
 * Date: 2019.03.13.
 * Time: 10:00
 */
class EmployeeWorkHours extends Model
{
    /**
     * Model Name
     *
     * @var string
     */
    protected $table = 'employee_work_hours';
    
    /**
     * Model Mass Assignments
     *
     * @var array
     */
    protected $fillable = [
        'employee_id',
        'start',
        'end'
    ];
    
    /**
     * Cast Type
     *
     * @var array
     */
    protected $dates = [
        'start',
        'end'
    ];
    
    /**
     * Mutator Getter
     *
     * @param $key $key data
     *
     * @return string
     */
    public function getStartAttribute($key)
    {
        return Carbon::parse($key)->format('H:i');
    }
    
    /**
     * Mutator Getter
     *
     * @param $key $key data
     *
     * @return string
     */
    public function getEndAttribute($key)
    {
        return Carbon::parse($key)->format('H:i');
    }
    
    /**
     * Mutator Getter
     *
     * @return float
     */
    public function getTotalHoursAttribute()
    {
        return round(Carbon::parse($this->start)->floatDiffInHours($this->end), 2);
    }
    
    /**
     * Relation
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }
}

resources/views/filter.blade.php
@extends('layouts.app')

@section('content')
    <div class="m-b-md">
        <h3 class="m-b-none">Filter 1</h3>
    </div>
    
    <form class="col-lg-12" action="{{ route('filter') }}" method="get" id="app">
        
        <div class="col-lg-3">
            <div class="form-group">
                <label for="sel1">Name:</label>
                <input type="text" name="name" value="{{ request()->get('name') }}" class="form-control" id="sel1">
            </div>
        </div>
        
        <div class="col-lg-3">
            <div class="form-group">
                <label for="sel1">From:</label>
                <datetime-component input-class="form-control" value="{{ request()->get('from') }}" type="date"
                                    name="from" id="sel1">{{ request()->get('from') }}</datetime-component>
            </div>
        </div>
        
        <div class="col-lg-3">
            <div class="form-group">
                <label for="sel1">Till:</label>
                <datetime-component input-class="form-control" value="{{ request()->get('till') }}" type="date"
                                    name="till" id="sel1">{{ request()->get('till') }}</datetime-component>
            </div>
        </div>
        
        <div class="col-lg-3" style="padding-top: 20px;">
            <button type="submit" class="btn btn-success">Filter</button>
        </div>
    
    </form>
    
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Company</th>
            <th>Employee</th>
            <th>Begin</th>
            <th>End</th>
        </tr>
        </thead>
        <tbody>
        
        @foreach($model_employee as $employee)
            <tr>
                <td>{{ $employee->company->name }}</td>
                <td>{{ $employee->fname }} {{ $employee->lname }}</td>
                <td>{{ $employee->workhours->getOriginal('start') }}</td>
                <td>{{ $employee->workhours->getOriginal('end') }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    
    {{ $model_employee->render() }}
@endsection

resources/views/filter2.blade.php
@extends('layouts.app')

@section('content')
    <div class="m-b-md">
        <h3 class="m-b-none">Filter 2</h3>
    </div>

    <div id="app">
        <filter2-component></filter2-component>
    </div>
@endsection

resources/views/filter3.blade.php
@extends('layouts.app')

@section('content')
    <div class="m-b-md">
        <h3 class="m-b-none">Filter 3</h3>
    </div>
    
    <form class="col-lg-12" action="{{ route('filter3') }}" method="get">
        
        <div class="col-lg-3">
            
            <div class="form-group">
                <label for="sel1">Filter list:</label>
                <select name="filter" class="form-control" id="sel1">
                    <option value="desc" @if (request()->get('filter') == 'desc') selected @endif>DESC</option>
                    <option value="asc" @if (request()->get('filter') == 'asc') selected @endif>ASC</option>
                </select>
            </div>
        
        </div>
        
        <div class="col-lg-3" style="padding-top: 20px;">
            <button type="submit" class="btn btn-success">Filter</button>
        </div>
    
    </form>
    
    {{--Issues with mutators--}}
    {{--<div id="app">--}}
    {{--<filter3-component></filter3-component>--}}
    {{--</div>--}}
    
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Company</th>
            <th>Employee</th>
            <th>Begin</th>
            <th>End</th>
            <th>Total Hours</th>
        </tr>
        </thead>
        <tbody>
        
        @foreach($model_employee_work_hours as $work_hours)
            <tr>
                <td>{{ $work_hours->employee->company->name }}</td>
                <td>{{ $work_hours->employee->fname }} {{ $work_hours->employee->lname }}</td>
                <td>{{ $work_hours->start }}</td>
                <td>{{ $work_hours->end }}</td>
                <td>{{ $work_hours->total_hours }}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    
    {{ $model_employee_work_hours->appends(Request::except('page'))->links() }}

@endsection